CI - fix running phpunit tests on PHP 7.2
A) phpunit + php 7.2
https://circleci.com/gh/costlocker/reports/13
https://github.com/sebastianbergmann/comparator/pull/30
https://github.com/EdgedesignCZ/phpqa/commit/9fe5cc9f11474859d9f196257382d7aec17bf96d
Fatal error: Declaration of SebastianBergmann\Comparator\DOMNodeComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) must be compatible with SebastianBergmann\Comparator\ObjectComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in /root/costlocker/reports/vendor/sebastian/comparator/src/DOMNodeComparator.php on line 110
```
composer remove phpunit/phpunit --dev
composer require phpunit/phpunit:~6 --dev
```

B) Ignored hamcrest assertions
https://github.com/phpspec/prophecy/issues/366#issuecomment-367711229
```
There were 21 risky tests:
1) Costlocker\Reports\DatesTest::testGetNextMonth with data set #0 ('2016-02-01', '2016-03')
This test did not perform any assertions
```